routes/web.php
<?php
use App\Sucursal;
use App\Models\Fiscal;
use App\Almacen;
use Illuminate\Contracts\Auth\Guard;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	$sucursal = Sucursal::get();
	$anio = Fiscal::where('codemp','>','010')->get();
     return view('auth.login')->with(['sucursal'=>$sucursal,'year' =>$anio]);
})->name('logins')->middleware('guest');//para que no me rediriga al login despues de haber sido logueado

//roles
 
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/modulo/ConfiguracionGenerales/Droles','RolesController@index')->name('rolesIndex')->middleware('permission:contenidos.index-,/modulo/ConfiguracionGenerales/Droles');

Route::get('/modulo/ConfiguracionGenerales/Droles/Delete/{id?}','RolesController@deleteRol')->name('rolesBorrar');
Route::get('/modulo/ConfiguracionGenerales/Droles/create/{id?}','RolesController@createRol')->name('rolescreate');
Route::post('/modulo/ConfiguracionGenerales/Droles/createRol','RolesController@createRoles')->name('rolescreates')->middleware('permission:contenidos.create-,/modulo/ConfiguracionGenerales/Droles');

///
// CAJA
Route::get('/modulo/ConfiguracionGenerales/Cajas/createcaja', 'CajaController@create')->name('cajaCreate')->middleware('permission:contenidos.create-,/modulo/ConfiguracionGenerales/Cajas');

Route::get('/modulo/ConfiguracionGenerales/Cajas/cajas', 'CajaController@index')->name('cajaList')->middleware('permission:contenidos.index-,/modulo/ConfiguracionGenerales/Cajas');

Route::post('/modulo/ConfiguracionGenerales/Cajas/insertcaja', 'CajaController@store')->name('cajaSave')->middleware('permission:contenidos.create-,/modulo/ConfiguracionGenerales/Cajas');

Route::get('/modulo/ConfiguracionGenerales/Cajas/editcaja/{id}', 'CajaController@show')->name('cajaEdit2')->middleware('permission:contenidos.edit-,/modulo/ConfiguracionGenerales/Cajas');
// CAJA //CAJAS no caja

Route::get('/modulo/ConfiguracionGenerales/Cajas', 'CajaController@index')->name('cajaList2')->middleware('permission:contenidos.index-,/modulo/ConfiguracionGenerales/Cajas');

Route::post('/modulo/ConfiguracionGenerales/Cajas/cajaSave', 'CajaController@store')->name('cajaSave2')->middleware('permission:contenidos.create-,/modulo/ConfiguracionGenerales/Cajas');

Route::get('/modulo/ConfiguracionGenerales/Cajas/cajaEdit/{id}', 'CajaController@show')->name('cajaEdit');

Route::put('/modulo/ConfiguracionGenerales/Cajas/cajaUpdate/{id}', 'CajaController@update')->name('cajaUpdate');

Route::get('/modulo/ConfiguracionGenerales/Cajas/cajaDelete/{id}', 'CajaController@destroy')->name('cajaDelete');

Route::get('/modulo/ConfiguracionGenerales/Cajas/cajaConf/{id}', 'CajaController@getconfview')->name('cajaConf');
Route::get('/modulo/ConfiguracionGenerales/Cajas/cajaConf/cajaReporte/{id}/{job}', 'CajaController@Reporte')->name('cajaReporte');

Route::post('/modulo/ConfiguracionGenerales/Cajas/cajaConf/getStatus/{id}', 'CajaController@getStatus')->name('getStatus');

Route::post('/modulo/ConfiguracionGenerales/Cajas/cajaConf/sendTickera/{id}', 'CajaController@sendTickera')->name('sendTickera');

Route::post('/modulo/ConfiguracionGenerales/Cajas/cambiarIva/{id}', 'CajaController@cambiarIva')->name('cambiarIva');


Route::get('/modulo/ConfiguracionGenerales/Cajas/buscarCaja', 'CajaController@filtro')->name('buscarCaja');

Route::get('/modulo/ConfiguracionGenerales/Cajas/IvaAdm/{id}', 'CajaController@IvaAdm')->name('IvaAdm')->middleware('permission:contenidos.index-,/modulo/ConfiguracionGenerales/Cajas/IvaAdm');


//////// CATEGORIAS

Route::get('/modulo/ConfiguracionGenerales/Categorias', 'CategoriasController@index')->name('categorias.index')->middleware('permission:contenidos.index-,/modulo/ConfiguracionGenerales/Categorias');

Route::get('/modulo/ConfiguracionGenerales/Categorias/create', 'CategoriasController@create')->name('categorias.create')->middleware('permission:contenidos.create-,/modulo/ConfiguracionGenerales/Categorias');

Route::post('/modulo/ConfiguracionGenerales/Categorias/sendCat', 'CategoriasController@store')->name('categorias.sendCat')->middleware('permission:contenidos.index-,/modulo/ConfiguracionGenerales/Categorias');

Route::post('/modulo/ConfiguracionGenerales/Categorias/getCat', 'CategoriasController@getCat')->name('categorias.getCat')->middleware('permission:contenidos.index-,/modulo/ConfiguracionGenerales/Categorias');

Route::get('/modulo/ConfiguracionGenerales/Categorias/edit/{id}', 'CategoriasController@edit')->name('categorias.edit')->middleware('permission:contenidos.edit-,/modulo/ConfiguracionGenerales/Categorias');

Route::put('/modulo/ConfiguracionGenerales/Categorias/update/{id}', 'CategoriasController@update')->name('categorias.update');

Route::delete('/modulo/ConfiguracionGenerales/Categorias/destroy/{id}', 'CategoriasController@destroy')->name('categorias.destroy');

// PAIS
Route::get('/modulo/ConfiguracionGenerales/DTerritorial/Pais','PaisController@index')->name('paisList')->middleware('permission:contenidos.index-,/modulo/ConfiguracionGenerales/DTerritorial/Pais');

Route::get('/modulo/ConfiguracionGenerales/DTerritorial/Pais/filtro','PaisController@filtro')->name('paisFiltro')->middleware('permission:contenidos.index-,/modulo/ConfiguracionGenerales/DTerritorial/Pais');

Route::get('/modulo/ConfiguracionGenerales/DTerritorial/Pais/paisCreate','PaisController@create')->name('paisCreate')->middleware('permission:contenidos.create-,/modulo/ConfiguracionGenerales/DTerritorial/Pais');

Route::get('/modulo/ConfiguracionGenerales/DTerritorial/Pais/paisEdit/{id}','PaisController@show')->name('paisEdit')->middleware('permission:contenidos.delete-,/modulo/ConfiguracionGenerales/DTerritorial/Pais');

Route::post('/modulo/ConfiguracionGenerales/DTerritorial/Pais/paisUpdate/{id}','PaisController@update')->name('paisUpdate')->middleware('permission:contenidos.delete-,/modulo/ConfiguracionGenerales/DTerritorial/Pais');

Route::post('/modulo/ConfiguracionGenerales/DTerritorial/Pais/paisSave','PaisController@store')->name('paisSave')->middleware('permission:contenidos.create-,/modulo/ConfiguracionGenerales/DTerritorial/Pais');

Route::get('/modulo/ConfiguracionGenerales/DTerritorial/Pais/paisDelete/{id}','PaisController@destroypais')->name('paisDelete')->middleware('permission:contenidos.delete-,/modulo/ConfiguracionGenerales/DTerritorial/Pais');
// ESTADO
Route::get('/modulo/ConfiguracionGenerales/DTerritorial/getEstJson/{id?}','EstadoController@getestadojson')->name('getEstJson')->middleware('permission:contenidos.index-,/modulo/ConfiguracionGenerales/DTerritorial/Estado');

Route::get('/modulo/ConfiguracionGenerales/DTerritorial/Estado','EstadoController@index')->name('estadoList')->middleware('permission:contenidos.index-,/modulo/ConfiguracionGenerales/DTerritorial/Estado');

Route::get('/modulo/ConfiguracionGenerales/DTerritorial/Estado/Filtro','EstadoController@filtro')->name('estadoFiltro');

Route::get('/modulo/ConfiguracionGenerales/DTerritorial/Estado/estadoCreate','EstadoController@create')->name('estadoCreate')->middleware('permission:contenidos.create-,/modulo/ConfiguracionGenerales/DTerritorial/Estado');//vista

Route::post('/modulo/ConfiguracionGenerales/DTerritorial/Estado/estadoSave','EstadoController@store')->name('estadoSave')->middleware('permission:contenidos.create-,/modulo/ConfiguracionGenerales/DTerritorial/Estado');//vista

Route::get('/modulo/ConfiguracionGenerales/DTerritorial/Estado/estadoShow/{id}','EstadoController@show')->name('estadoShow')->middleware('permission:contenidos.index-,/modulo/ConfiguracionGenerales/DTerritorial/Estado');//vista

Route::put('/modulo/ConfiguracionGenerales/DTerritorial/estadoUpdate/{id}','EstadoController@update')->name('estadoUpdate')->middleware('permission:contenidos.edit-,/modulo/ConfiguracionGenerales/DTerritorial/Estado');//vista

Route::get('/modulo/ConfiguracionGenerales/DTerritorial/estadoDelete/{id}','EstadoController@destroyest')->name('estadoDelete')->middleware('permission:contenidos.index-,/modulo/ConfiguracionGenerales/DTerritorial/Estado');//vista


//CONFIGURACIONES GENERALES PROMOCIONES

Route::get('/modulo/Almacen/Promociones','PromocionesController@index')->name('promociones')->middleware('permission:contenidos.index-,/Almacen/Promociones');
Route::get('/modulo/Almacen/Promociones/Edit/{id}','PromocionesController@infoupdate')->name('editpromociones')->middleware('permission:contenidos.edit-,/Almacen/Promociones');
Route::get('/modulo/Almacen/Promociones/Detalles/{id}','PromocionesController@detalles')->name('detalles.promociones')->middleware('permission:contenidos.edit-,/Almacen/Promociones');
Route::post('/modulo/Almacen/Promociones/ArticuloAlmacen','PromocionesController@getArticuloAlmacen')->name('articuloPorAlamacen.promociones');
Route::get('/modulo/Almacen/Promociones/Buscarpromocion','PromocionesController@filtro')->name('filtro.promociones');
Route::get('/modulo/Almacen/CrearPromociones','PromocionesController@create')->name('promociones.crear')->middleware('permission:contenidos.create-,/Almacen/Promociones');
Route::post('/modulo/Almacen/Promociones/Anular','PromocionesController@anularArticulo')->name('promociones.anular')->middleware('permission:contenidos.edit-,/Almacen/Promociones');
Route::post('/modulo/Almacen/Promociones/Activar','PromocionesController@activateArticulo')->name('promociones.activo')->middleware('permission:contenidos.edit-,/Almacen/Promociones');
Route::get('/modulo/Almacen/CrearPromociones/getinfo','PromocionesController@getinfo')->name('getinfo.promociones');

app/Audit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;

class Audit extends Model
{
    use SoftDeletes;
    protected $connection = 'pgsql';
    protected $table = 'audits';
    protected $fillable = ['old_values','new_values'];
    
    public function user()
    {
        return $this->hasOne(User::class,'codigoid','user_id');
    }

    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->format('d/m/Y H:i');
    }

    public function getEventAttribute($value)
    {
        return strtoupper($value);
    }

}

app/Http/Controllers/RolesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\HomeController;
use App\rolesusuarios;
use Helper;
use Session;
use Illuminate\Support\Facades\Auth;
use App\Segususuc;

class RolesController extends Controller
{
    
    public function __construct()
    {
    	$this->middleware('auth');
    }

	public function index()
	{
		$menu = new HomeController();
		$roles = rolesusuarios::paginate(8);
		return view('configuracionGenerales.roles.listasRoles')->with('menus',$menu->retornarMenu())->with('roles',$roles)->with('sec',Segususuc::where('codusuario',Auth::user()->codigoid)->where('activo','TRUE')->first()->getSucursal->nomsucu);
	}

	public function deleteRol($id)
	{
		$desc=Helper::desencriptar($id);
        $sep  = explode('-',$desc);
        $ID = $sep[1].'-'.$sep[2];
		#dd($sep);
		
		$delete = \App\rolesusuarios::where('codigoid',$ID)->delete();
		return response()->json([
			'titulo' => 'SE HA ELIMINADO CON EXITO'

		]);
	}

	public function createRol()
	{
		 $menu = new HomeController();

		 return view('configuracionGenerales.roles.crearRoles')->with('menus',$menu->retornarMenu());
	}

	public function createRoles(Request $request)
	{	
		$request->validate([

			'codigos' => 'required',
			'nomCargo'=> 'required'
		]);
		$menu = new HomeController();
		$roles = rolesusuarios::paginate(8);
		
		
		$search = rolesusuarios::where('codroles',$request->codigos)->first();
		
		if (is_null($search) === false) {
		Session::flash('error', 'Este rol se encuentra registrado');
		
		return redirect()->route('rolesIndex')->with('menus',$menu->retornarMenu())->with('roles',$roles);
			
		}else{


			$sucuse_reg=Auth::user()->getsucUse()->codsuc;
            $guion='-';
            $cont = rolesusuarios::withTrashed()->get()->count();
            $cont = $cont+1;
            $suc = Auth::user()->codsuc_reg;
            $codsuc_reg = explode('-',$suc);
            $cod = $cont.$guion.$codsuc_reg[1];

			rolesusuarios::create([
				'codroles' => $request->codigos,
				'nombre' => $request->nomCargo,
				'codsuc_reg' => $suc,
				'codigoid' => $cod
			]);

			Session::flash('success', 'Se ha registrado con exito');
		
			return redirect()->route('rolesIndex')->with('menus',$menu->retornarMenu())->with('roles',$roles);

		}


		
	}

}

resources/views/configuracionGenerales/roles/crearRoles.blade.php
@extends('layouts.app')
@extends('layouts.menu')
@section('titulo','Registrar Articulos')
  @section('content')
    @component('layouts.contenth')
    @slot('titulo')
      Crear Cargos
    @endslot
  @endcomponent
    
    <section class="content-wrapper" >
    <div class="container-fluid">
    <div class="container">
        
        <div class="col-10">
            <!-- general form elements -->
            <div class="card card-info" style="padding-right: -1000px">
              <div class="card-header">
                <h3 class="card-title"><b>REGISTRAR CARGOS</b></h3>
                
              </div>
              <!-- /.card-header -->
              <!-- form start -->
             
              <form action="{{route('rolescreates')}}" method="post"> 
              {{csrf_field()}}
                <div class="card-body" >
                 <div class="row">
                 <div class="col-sm-6">
                 <div class="form-group">
                  <label for="tipodocumento">C&oacute;digo</label>
                     <div class="input-group mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text">A-1</span>
                  </div>
                  <input type="text" class="codigo form-control" placeholder="Ejem: R-002" name="codigos" 
                  id="cedularifcliente" class="@error('codigos') is-invalid @enderror" maxlength="13"
                  
                  >
                </div>
                @error('codigos')
                  <div class="alert alert-danger">{!!$message!!}</div>
                @enderror
                </div>     
                 </div>
                 
               <div class="col-sm-6">
                <div class="form-group">
                <label>Nombre del Cargo</label>
                <div class="input-group mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text">A</span>
                  </div>
                  <input type="text" class="form-control desc" placeholder="Ejem: 1234567" name="nomCargo" 
                  id="cedularifcliente" class="@error('Descripcion') is-invalid @enderror">
                </div>
                @error('Descripcion')
                  <div class="alert alert-danger">{!!$message!!}</div>
                @enderror
                </div>
               </div>
               </div>
               <div class="form group detalle">
                
               <div class="card-footer">
                <button type="submit" class="btn btn-success"><b>Guardar Cambios</b></button>

                 <a href="{{ url('/modulo/ConfiguracionGenerales/Droles') }}" class="btn btn-default"><i class="fa fa-chevron-circle-left"></i> Volver</a>
                </div>
               </div>
            <!-- /.card -->
           </div>
            <!-- /.col-lg-6 -->
          </div>
            <!-- /.row -->

         </form>
      
        </div>
            <!-- /.card -->
       </div>
      </div>
      </div>
  </section>
  @endsection

  @section('mayuscula')
  
  @endsection
    

resources/views/configuracionGenerales/roles/listasRoles.blade.php
@extends('layouts.app')
@extends('layouts.menu')
@section('titulo','Reiniciar Contraseña')

@section('content')

@component('layouts.contenth')
    @slot('titulo')
      Listados de Roles
    @endslot
@endcomponent
    <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-12">
            <div class="card">
              @include('vendor/flash.flash_message')
              <div class="card-header">
                <h3 class="card-title"><b></b></h3>

                <div class="card-tools">
                 <div class="row">

              <div class="col">
                  <div class="row">
                    <div class="col-xs-12">
                      
                        <form method="post" action="{{ route('filtro') }}">
                            <div class="input-group">
                             @csrf
                             @can('create',App\permission_user::class)
                          <div class="card-tools mr-2">
                            @can('create',App\permission_user::class) 
                            <a href="{{ route('rolescreate') }}" class="btn btn-info"><b>REGISTRAR CARGOS</b></a>
                            @endcan
                          </div>
                          @endcan
                          <input type="text" placeholder="Buscar por nombre de Usuario" name="filtro" class="form-control float-right">
                          
                          <button type="submit" style="height: 38px; width: 38px" class="btn btn-default btn-sm float-left"><i class="fas fa-search"></i></button>
                           
                           </div>
                        </form>
                     
                    </div>
                  </div>
                 </div>
                
                 </div><!--row -->
                </div>
              </div>

              <!-- /.card-header -->
              <div class="card-body table-responsive p-0 text-center">
                <table class="table table-hover">
                  <thead>
                    <tr style="text-align:center">
                      <th>ID</th>
                      <th>Codigo del rol</th>
                      <th>nombre</th>
                      
                      <th>Fecha</th>
                     
                      <th>Accion</th>

                    </tr>
                  </thead>
                  <tbody style="text-align:center">

                    @foreach ($roles as $element)
                    @php
                      $rand  = rand(1, 9999);
                      $nrand = str_pad($rand,4,'0',STR_PAD_LEFT);
                      $enc=Helper::EncriptarDatos($nrand.'-'.$element->codigoid);
                      //$borr=Helper::EncriptarDatos($nrand.'|'.$tal->id.'|'.$tal->codigoid);
                    @endphp
                     <tr style="text-align: center;">
                      <td>{{$element->id}}</td>
                      <td>{{$element->codroles}}</td>
                      <td>{{$element->nombre}}</td>
                      <td>{{$element->created_at}}</td>
                      <td>
                       @can('delete',App\permission_user::class) 
                        <a class="borrar" href="{{ route('rolesBorrar',$enc) }}">
                          <i class="fa fa-trash blue"></i>
                        </a>
                       @endcan
                      </td>
                        
                    @endforeach
                        
                  </tbody>
                </table>
                   {{$roles->appends(Request::only('filtro'))->render()}}

          </div>
          </div>
        </div>
    </div>
      {{-- row --}}
{{--   --}}
                  
  </div>
@endsection


@section('script')
<script>
  $(document).ready(function(e) {
    

    $('a.borrar').on('click',function (e) {
        e.preventDefault();
             Swal.fire({
            title: '¿Seguro que desea eliminar este Cargo?',
            text: "¡Despues de esto no se encontrara en la lista!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Si, eliminar'
          }).then((result) => {
              if (result.value == true) {

                
              var row = $(this).parents('tr');
              //var form = $(this).parents('data-id');
              var url = $(this).attr('href');
              //console.log(url);
              $.get(url,row,function(result1) {
                  
                if (result1.titulo === 'SE HA ELIMINADO CON EXITO') {

                  
                      Swal.fire(
                        'SE HA ELIMINADO CON EXITO',
                        '.',
                        'success',

                      );

                      row.fadeOut();
                }

                                           
                 

              })   
              }  //para cancelar el sweetalert2
          });
    })

  });
</script>
@endsection